[package]
name = "miner"
version = "0.1.0"
edition = "2024"

[dependencies]
btclib = { path = "../lib" }
tokio = { version = "1.49.0", features = ["full"] }
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
flume = "0.12.0"
